//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheModernBibliotheca._Code.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int BorrowID { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public string ReservationStatus { get; set; }
        public System.DateTime DateProcessed { get; set; }
    
        public virtual Borrow Borrow { get; set; }
    }
}
