//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheModernBibliotheca._Code.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public int UserActivityId { get; set; }
        public int UserID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual LibraryUser LibraryUser { get; set; }
    }
}
